# Make file include
#CC	= /home/nick/dev/tplink/toolchain-mips_r2_gcc-4.3.3+cs_uClibc-0.9.30.1/usr/bin/mips-openwrt-linux-gcc
CC		= gcc
PRJCFLAGS = -g
#LD 	= /home/nick/dev/tplink/toolchain-mips_r2_gcc-4.3.3+cs_uClibc-0.9.30.1/usr/bin/mips-openwrt-linux-gcc
LD		= gcc
LDFLAGS =
AR		= ar
ARFLAGS = 
RANLIB	= ranlib
RM		= rm
ECHO	= echo

SHELL	= /bin/sh

.SILENT :
